services:
  postgres:
    image: 'postgres:16.10-alpine3.22'
    restart: always
    container_name: 'postgres'
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DATABASE=${PG_DATABASE}
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${PG_PORT}", "-U", "${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3
  
  minio:
    image: 'minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1'
    restart: always
    container_name: 'minio'
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=http://0.0.0.0:${MINIO_PORT}
      - MINIO_BROWSER_REDIRECT_URL=http://0.0.0.0:${MINIO_CONSOLE_PORT}
    volumes:
      - './minio/data:/data'
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mlflow-tracking-server:
    build: ./mlflow
    restart: always
    container_name: 'mlflow-tracking-server'
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_S3_IGNORE_TLS=true
      - HOME=/home/mlflow. # Исправляет ошибку при регистрации модели. Странно, но работает)
    command: >
      mlflow server
      --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --artifacts-destination s3://${MLFLOW_BUCKET_NAME}/
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/')"]
      interval: 30s
      timeout: 10s
      retries: 3


  mlflow-create-buckets:
    image: 'minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1'
    container_name: 'mlflow-create-buckets'
    depends_on:
      minio:
        condition: service_healthy
    profiles:
      - donotstart
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      until (/usr/bin/mc alias set s3 http://minio:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb s3/${MLFLOW_BUCKET_NAME};
      /usr/bin/mc anonymous set download s3/${MLFLOW_BUCKET_NAME};
      exit 0;
      "